version: "3.9"
services:
  database:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=webapi
      - POSTGRES_PASSWORD=webapi
      - POSTGRES_DB=webapi
  
  ipfs:
    image: ipfs/kubo:latest
    ports:
      - 4001:4001/udp
      - 4001:4001
      - 5001:5001
      - 8080:8080
    environment:
      - IPFS_PATH=/ipfs_data
    volumes:
      - ./decentraveller-ipfs:/ipfs_data

  api:
    build: decentraveller-api/
    command: poetry run uvicorn src.app:app --host 0.0.0.0 --log-level debug
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://webapi:webapi@database:5432/webapi
      - WEAVIATE_DATABASE_URL=http://weaviate:8080
      - IPFS_NODE_URL=http://ipfs:5001
      - ML_API_URL=http://ml-api:8000
      - PYTHONHASHSEED=0
      - INDEXER_API_KEY=asd123
      - BLOCKCHAIN_RPC_URL=http://blockchain:8545
      - DEEP_LINK_SCHEME=exp://192.168.1.115:19000/--/
    env_file:
      - decentraveller-api/geocoding.env
    depends_on:
      - database
      - weaviate
      - ipfs
      - ml-api
      - blockchain
    restart: on-failure:3

  ml-api:
    build: decentraveller-ml-api/
    command: poetry run gunicorn -b 0.0.0.0:8000 -w 1 'main:app'
    expose:
      - 8000
    ports:
      - 8001:8000
  
  blockchain:
    build: decentraveller-blockchain/
    command: yarn start:local
    expose:
      - 8545
    ports:
      - 8545:8545

  indexer:
    build: decentraveller-indexer/
    command: npm start
    environment:
      - BLOCKCHAIN_URI=http://blockchain:8545
      - API_ENDPOINT=http://api:8000
      - INDEXER_API_KEY=asd123
    depends_on:
      - blockchain
    restart: on-failure:3
  
  weaviate:
    image: semitechnologies/weaviate:1.19.2
    expose:
      - 8080
    ports:
      - 8085:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  embedding_updater_job:
    build: decentraveller-recsys/
    command: python main.py
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://webapi:webapi@database:5432/webapi
      - WEAVIATE_DATABASE_URL=http://weaviate:8080
    depends_on:
      - database
      - weaviate
