version: "3.9"
services:
  database:
    image: postgres:15
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=webapi
      - POSTGRES_PASSWORD=webapi
      - POSTGRES_DB=webapi

  api:
    build: decentraveller-api/
    command: uvicorn src.app:app --host 0.0.0.0 --log-level debug
    ports:
      - 8000:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://webapi:webapi@database:5432/webapi
    depends_on:
      - database
  
  blockchain:
    image: decentraveller-blockchain:latest
    command: yarn start:local
    expose:
      - 8545
    ports:
      - 8545:8545

  indexer:
    image: decentraveller-indexer:latest
    command: npm start
    environment:
      - BLOCKCHAIN_URI=http://blockchain:8545
    depends_on:
      - blockchain
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2