version: "3.9"
services:
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=webapi
      - POSTGRES_PASSWORD=webapi
      - POSTGRES_DB=webapi

  api:
    build: decentraveller-api/
    command: uvicorn src.app:app --host 0.0.0.0
    ports:
      - 8008:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://webapi:webapi@db:5432/webapi
    depends_on:
      - database
  
  blockchain:
    build: decentraveller-blockchain/
    command: yarn start:local
    expose:
      - 8545
    ports:
      - 8545:8545

  indexer:
    build: decentraveller-indexer/
    command: npm start
    environment:
      - BLOCKCHAIN_URI=http://blockchain:8545
    depends_on:
      - blockchain
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2

volumes:
  postgres_data: