services:
  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=webapi
      - POSTGRES_PASSWORD=webapi
      - POSTGRES_DB=webapi

  tests:
    build: .
    command: pytest tests

  api:
    build: .
    command: uvicorn src.app:app --host 0.0.0.0
    ports:
      - 8008:8000
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://webapi:webapi@db:5432/webapi
    depends_on:
      - database

volumes:
  postgres_data: