name: Tests
run-name: ${{ github.actor }} 
on: [push]
jobs:

  api_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker-compose -f docker-compose-tests.yml run api-unit-tests

  integration_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y wget openimageio-tools
    - name: Build images
      run: make docker-image
    - name: Run environment
      run: make docker-compose-up 
    - name: Sleep Action
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 5s
    - name: Log docker
      run: docker-compose logs
    - name: Load sample data
      run: docker-compose -f docker-compose-tests.yml run load-sample-data
    - name: Log docker
      run: docker-compose logs
    - name: Check ETL
      run: ./check_status.sh

  blockchain_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: docker-compose build blockchain
      - name: Test blockchain
        run: docker-compose run --entrypoint "yarn hardhat test" blockchain



