name: Web API tests
run-name: ${{ github.actor }} 
on:
  push:
    paths:
      - decentraveller-api
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose run api-tests
