name: Tests
run-name: ${{ github.actor }} 
on: [push]
jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker-compose -f docker-compose-tests.yml run api-tests
