name: Tests
run-name: ${{ github.actor }} 
on: [push]
jobs:
  api_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: docker-compose -f docker-compose-tests.yml run api-unit-tests
  integration_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run environment
      run: docker-compose up -d
    - name: Load sample data
      run: docker-compose -f docker-compose-tests.yml run load-sample-data
    - name: Load sample data
      run: ./check_status.sh

